[default]

[testing]
host="some.host"
username="admin"
password="password"

[iosxe-recomm]
host="sandbox-iosxe-recomm-1.cisco.com"
netconf.port=830
restconf.port=443


[iosxe-latest]
host="sandbox-iosxe-latest-1.cisco.com"
netconf.port=830
restconf.port=443


[nxos]
host="sbx-nxos-mgmt.cisco.com"
netconf.port=830
restconf.port=443
nxapi.port=443
